### ISSUE TITLE
Outdated version of Gregorio?

### ISSUE THREAD

**Issue by cwrinn** [bbloomf/jgabc#26]
I reported a similar issue over on [GregoBase](https://github.com/gregorio-project/GregoBase/issues/12), but it is happening in jgabc as well (in fact, this is where my schola noticed the issue).

I'm reporting over here as well for your benefit.

Gloria XI is not rendering a quilisma in the final Patris before the Amen. It works fine when I run the gabc manually in Gregorio 5.0.1.

**Comment by bbloomf** [comment]
Thanks, I will get this fixed soon.

**Comment by bbloomf** [comment]
Fixed.

**Comment by cwrinn** [comment]
Has this fix made it to the mobile apps yet? My android phone still doesn't render that as a quilisma. Works in Chrome.

**Comment by bbloomf** [comment]
No, some other things came up, and I forgot to put out a new version of the Android app.  I just put out the release now, though, after reading your comment.
